### ISSUE TITLE
Some questions about TITER

### ISSUE THREAD

**Issue by YuLiu61** [zhangsaithu/titer#1]
I downloaded the codes, data, and models before. I'd like to repeat the experiment. However, the results is not the same as yours. Besides, I can not find the models now. Would you mind telling me the reason?

**Comment by YuLiu61** [comment]
![TITER](https://user-images.githubusercontent.com/41932803/54473836-1e85a200-4818-11e9-946f-707e9c458276.png)

**Comment by zhangsaithu** [comment]
Hi, @YuLiu61 Thanks for putting forward this issue. Recently we noticed some issue about the previous model files and have just re-uploaded the models. These files can work perfectly to reproduce the paper's result.

**Comment by YuLiu61** [comment]
Thanks for your reply and re-uploading the models. However, I can’t reproducing the paper's result. The program always reports an error. I don’t know why. The newest result can be seen in the attachment.
I would be appreciate it a lot if you can help me.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用[cid:image002.png@01D4DD16.1456F850]

________________________________
发件人: zhangsaithu <notifications@github.com>
发送时间: Sunday, March 17, 2019 9:40:40 AM
收件人: zhangsaithu/titer
抄送: YuLiu61; Mention
主题: Re: [zhangsaithu/titer] Some questions about TITER (#1)


Hi, @YuLiu61<https://github.com/YuLiu61> Thanks for putting forward this issue. Recently we noticed some issue about the previous model files and have just re-uploaded the models. These files can work perfectly to reproduce the paper's result.

―

**Comment by nonnerdling** [comment]
Hi @YuLiu61, I cannot see your attachment here. Please send your problem to huhailin92@gmail.com if you need any help.
